if (NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "INPUT and OUTPUT must be defined")
endif()

get_filename_component(INPUT_NAME "${INPUT}" NAME)
string(REGEX REPLACE "[^A-Za-z0-9]" "_" VAR_NAME "${INPUT_NAME}")

file(READ "${INPUT}" INPUT_HEX HEX)
string(LENGTH "${INPUT_HEX}" INPUT_HEX_LEN)
math(EXPR BYTE_COUNT "${INPUT_HEX_LEN} / 2")

set(HEADER_TEXT "unsigned char ${VAR_NAME}[] = {\n")
if (BYTE_COUNT GREATER 0)
    math(EXPR LAST_BYTE_INDEX "${BYTE_COUNT} - 1")
    foreach(BYTE_INDEX RANGE 0 ${LAST_BYTE_INDEX})
        math(EXPR HEX_INDEX "${BYTE_INDEX} * 2")
        string(SUBSTRING "${INPUT_HEX}" ${HEX_INDEX} 2 HEX_BYTE)
        string(APPEND HEADER_TEXT "0x${HEX_BYTE}")
        if (NOT BYTE_INDEX EQUAL LAST_BYTE_INDEX)
            string(APPEND HEADER_TEXT ", ")
        endif()
        math(EXPR LINE_BREAK_CHECK "(${BYTE_INDEX} + 1) % 12")
        if (LINE_BREAK_CHECK EQUAL 0)
            string(APPEND HEADER_TEXT "\n")
        endif()
    endforeach()
endif()
string(APPEND HEADER_TEXT "\n};\nunsigned int ${VAR_NAME}_len = ${BYTE_COUNT};\n")

file(WRITE "${OUTPUT}" "${HEADER_TEXT}")
